development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: library_technology_development
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: library_technology_test
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: library_technology_production
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock
